services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: planning-poker-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: planning-poker
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - planning-poker-network

  # Planning Poker Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: planning-poker-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/planning-poker?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 7d
      COOKIE_SECRET: your-cookie-secret-key-change-in-production
      CLIENT_URL: http://localhost:5000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - planning-poker-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  planning-poker-network:
    driver: bridge 